services:
  frontend:
    build: ./frontend
    restart: unless-stopped

  backend:
    build: ./backend
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mosquitto

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "2080:80"
      - "2443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
    depends_on:
      - frontend
      - backend

# for testing purposes only!
# expose the MQTT broker on a non-standard port to avoid conflicts with any local installations
  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "2883:2883"
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro


volumes:
  caddy_data:
